### ISSUE TITLE
Add address / ENS name viewer component

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#156]
Should include the identicon image too

**Comment by bpierre** [comment]
# Identity Component proposal

The identity component will be used to display an Ethereum address or a label representing that address.

## Motivation

The Aragon UI Badge component is currently used to represent Ethereum addresses and Aragon ID domains:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/36158/39527686-f9220718-4e19-11e8-89f1-c90da0a59e4e.png">

That solution comes with some issues:

- Addresses are long and require a lot of horizontal space.
- The Ethereum address is not visible when an Aragon ID domain is used.
- Being able to copy an Ethereum address should be a core feature, the same way copying URLs is in web browsers (e.g. right click → “Copy Link Location” in Firefox or long press → “Copy” in Safari iOS). A standard way to copy addresses would be beneficial.

## Requirements

- The address behind the label can always be accessed, be selectable and copyable.
- The history of the address can be verified (e.g. on Etherscan).
- The address can be copied in the clipboard.
- Limiting the width of the component should not compromise the experience.

## The Badge

The component appears as a badge, whose label represent something that points to an Ethereum address.

An Ethereum address:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/36158/39526109-ba103eea-4e15-11e8-850b-2b0967bc6190.png">


An ENS domain:

<img width="201" alt="image" src="https://user-images.githubusercontent.com/36158/39526138-ca6b69c2-4e15-11e8-8359-f7d770a13dd3.png">

Or a name:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/36158/39526146-d3581eea-4e15-11e8-8767-9ebb575ecce7.png">

The badge can be shortened if needed:

<img width="159" alt="image" src="https://user-images.githubusercontent.com/36158/39526169-e0d012ee-4e15-11e8-9db6-3b40ca7d44df.png">

## The Box

When the badge is clicked, a box appears with the address corresponding to the badge.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/36158/39527810-4dc60f6c-4e1a-11e8-9eea-ae7b40b87299.png">


The box contains the following elements:

- The label used for the badge, not shortened. If the badge was displaying an Ethereum address already, the label is not displayed.
- The Ethereum address itself, already selected. That way, the action of copying an address should require the same amount of effort as selecting an address to copy it.
- A “copy to clipboard” button to make it even easier to copy the address.
- The blocky image of the address (https://github.com/ethereum/blockies).
- A close button. I think it might also be a good idea to close it when anything else is focused / clicked outside the box. The reason is that an identity badge could be clicked by inadvertently clicked, and having to reach the close button could be confusing. There is no complex action in this box, so it shouldn’t be a problem.
- A link to etherscan.

## Notes

The address input component is addressed in this issue: aragon/aragon-ui#149.

The Ethereum address + blockies image duo could be designed in a way that it can be reused in the address input component.

Should we cut in the middle in the case of a shortened Ethereum address, the same way the Ledger Nano S does? I guess the reason is to allow a visual check in two steps, using the first and last groups of characters, instead of a longer group of chars at the beginning.

We might want to display some additional information:

- Indicate if the address is the one provided by the wallet (“you”).
- Account type (Aragon Organization, Aragon App, other contract, normal account).
- Ether balance?
- In the future, we will probably want to display here some off chain information linked to Aragon ID: name, avatar, etc.

@aragon/aragon-core Thoughts?

**Comment by luisivan** [comment]
Agree on splitting the address in the middle.
Also it'd be great to show the avatar/identicon by default too.
Good work!
