### ISSUE TITLE
Add a width or wide prop to the Slider Component

### ISSUE THREAD

**Issue by ottodevs** [aragon/aragon-ui#227]
Right now the slider component's width is hardcoded, its use is hard sometimes with that limitation, since any external style rule seems to be overwritten with the default style.

The `wide` prop like the Button component should allow to correctly position the Slider inside any container.

Maybe I could PR the solution if you find it interesting to have
Thanks for your attention !

**Comment by bpierre** [comment]
I don’t think it is? [Only the `min-width` is](https://github.com/aragon/aragon-ui/blob/master/src/components/Slider/Slider.js#L11) (10x the width of the handle), but we could make it configurable as well.

**Comment by ottodevs** [comment]
After reviewing the case I think it must be a way to change the style by targeting specific CSS selectors, but I couldn't manage to do it by myself, could it be possible that the Spring component or any other specificity rule is preventing my styles to be applied?

We ended up overriding the Slider component to change 3 CSS properties: the `Area` `width:`, and `Bars` and `Handle` `left:`
https://github.com/Giveth/planning-app/blob/dev/apps/range-voting/app/components/Slider.js

**Comment by bpierre** [comment]
> After reviewing the case I think it must be a way to change the style by targeting specific CSS selectors, but I couldn't manage to do it by myself, could it be possible that the Spring component or any other specificity rule is preventing my styles to be applied?

We should probably avoid extending the style of components by using CSS selectors, because it would break as soon as the internal structure changes. But we could let users extend the styles of specific components by providing dedicated props? e.g. `areaStyle`, `barStyle` and `handleStyle`.

Or maybe we could directly let people specify components? That way we could export them (`Slider.Handle`, …), which would allow people to extend them if needed:

```jsx
const MyHandle = styled(Slider.Handle)`
  border-radius: 0;
`

const App = () => <Slider handle={<MyHandle />} />
```

To allow full customization, it would also require to be able to pass some other things like `getHandleStyles`. What do you think?

Also, I wonder why changing these CSS properties was needed? It seems like the slider were not adapting to its width in your context, maybe it’s something that can be fixed in the component?
