### ISSUE TITLE
SidePanel: add render prop with the open status

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#347]
See https://github.com/aragon/aragon-apps/pull/717#discussion_r272848595.

Nested components to the `SidePanel` will likely want to do different things based on whether or not it's opened.

**Comment by kushagrasharma** [comment]
Hi! I'm interested in working on this issue. Seems like a good place to start for someone new to the project.

Since I am new, what's the best way to get onboarded to contributing to Aragon UI/Aragon as a whole? I didn't see a contributors doc, are there best practices, tests, a chat, or anything else like that I should know about before diving in?

Thanks 😄

**Comment by bpierre** [comment]
Hi @kushagrasharma, that’s great! Yes it would be nice to have access to this information, let me know if you want to discuss anything before opening your first PR!

> Since I am new, what's the best way to get onboarded to contributing to Aragon UI/Aragon as a whole? I didn't see a contributors doc, are there best practices, tests, a chat, or anything else like that I should know about before diving in?

The chat is generally a good place to start with, you could join the `#dev` and `#dev-frontend` channels on https://aragon.chat/home (I am `@bpierre` there too).

A proper contributor’s guide is coming to aragonUI, but in the meantime, you can check these two documents:

- https://github.com/aragon/aragon-apps/blob/master/CONTRIBUTING.md
- https://gist.github.com/bpierre/22572415b90577aa17e5953fa68980eb

Talk to you soon :hugs:

**Comment by bpierre** [comment]
Done in https://github.com/aragon/aragon-ui/pull/616
