### ISSUE TITLE
IdentityBadge: focus ring on compact version can look cut off

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#374]
<img width="332" alt="Screen Shot 2019-05-15 at 1 29 54 PM" src="https://user-images.githubusercontent.com/4166642/57772460-c125a880-7715-11e9-9cc1-ae955ddc3bad.png">

Since these are used as inline items, we may want to remove or reduce the size of the focus ring around them.

**Comment by bpierre** [comment]
Removing would break keyboard navigation so I wouldn’t consider it an option, but I see two things here:

- For this component specifically, we should ensure the vertical lines of the outline land a bit more on the inside.
- Ideally, every time we use `overflow: hidden` (or have a component positioned next to the viewport limits), we should either ensure that there is enough space to not cut the outline, or slightly adapt the focus ring so that it doesn’t get outside (e.g. for the top of `MenuPanel` in the Aragon client).

**Comment by sohkai** [comment]
Fixed with the new IdentityBadges.
