### ISSUE TITLE
Markdown rendering component

### ISSUE THREAD

**Issue by corydickson** [aragon/aragon-ui#386]
As discussed in the all devs call here are the several implementations of markdown editing across various ecosystem apps:

- https://github.com/aragon/aragon/blob/e1ad4a8d7f2eae7a9b05d08794da9e700a5c35fa/src/components/Markdown/Markdown.js

- https://github.com/pandonetwork/pando/pull/64

- Aragon Home (Autark):

![image](https://user-images.githubusercontent.com/7246942/58483742-1d021f80-8161-11e9-86e1-028b723d8974.png)

We need to come to a consensus about which dependencies to use, the three under consideration are: [CodeMirror](https://codemirror.net/), [remark](https://github.com/remarkjs/remark), and [markdown-it](https://github.com/markdown-it/markdown-it). So far we have implementations using the former two options.

Core Features:
- Preview changes
- Syntax highlighting 
- Editing toolbar w/ clickable icons (as shown from the screenshot) 
- Responsive, can be dropped in the `SidePanel` component but also be full-width of a `Card`

**Comment by chadoh** [comment]
We've all-but-finished Autark's implementation of a MarkdownPreview component; see https://github.com/AutarkLabs/aragon-home/pull/16

Some highlights:

* Using [react-markdown](https://github.com/rexxars/react-markdown) (built on top of [remark](https://github.com/remarkjs/remark)) instead of [markdown-react-js](https://github.com/alexkuz/markdown-react-js) (built on top of [markdown-it](https://github.com/markdown-it/markdown-it)) – see [the commit where this was changed](https://github.com/AutarkLabs/aragon-home/pull/16/commits/3cbc6190b551c3b2d0b73bcba77ab044f5dd3926) for some justification
* Replaces `<a>` elements with [aragonUI `SafeLink`](https://ui.aragon.org/safe-link/)
* Supports GitHub-style task lists (using `- [ ]` and `- [x]`), using an [aragonUI `CheckBox`](https://ui.aragon.org/check-box/), but does not yet support clicking a checkbox in Preview mode to automatically update the saved content

I discussed how this could evolve into `aragonUI` additions with @bpierre; here's what we came up with:

* Given that people may want to _style a chunk of HTML content with expectable styles_ separately from _converting Markdown to HTML_, we can add two new components to `aragonUI`; for now let's call them `<NormalizedHtml>` and `<RenderedMarkdown>`, to be used in conjunction like this:

    ```js
    <NormalizedHtml>
      <RenderedMarkdown content={userDefinedStuff} />
    </NormalizedHtml>
    ```

* `NormalizedHtml` will perform "default aragonUI" styling operations, where an `h1` inside this component looks like a `<Text size="xxlarge">` component, but with margin+padding expectable for a blob of text content

* `NormalizedHtml` will use existing aragonUI styles as much as possible, by using `font()` and similar

  * We also discussed how to improve the reusability of the styles currently accessible [via `font()`](https://github.com/aragon/aragon-ui/blob/master/src/utils/styles/font.js#L48), though we do not feel confident with a recommendation on this. We considered the possibility of exporting style objects, for use with `styled-components` or inline React styles, like so:

      ```js
      import { styles } from 'aragonUI/Text'
      const MyComponent = styled.h1(styles.xxlarge)
      ```
  * Such code reorganization may simplify the effort to build a `NormalizedHtml` component, but is not a prerequisite

* `RenderedMarkdown` will do no styling of its own

* `RenderedMarkdown` will perform the `CheckBox` and `SafeLink` interpolation, as well as any other security measures, and could also eventually implement the "clicking a task list checkbox updates the source markdown" behavior

**Comment by gh1dra** [comment]
Just a few questions for creating this exportable `style` object for @chadoh :

- Why would we organize our styles around the `Text` component as it is already pretty generic allowing the user to change the font-weight etc. Maybe instead inside theme we have some predefined styles based off of the design system?

- Also the `rem` sizes don't really match 1-to-1 from your PR with the base `font-size: 15px`, let me know if the h1 being `great` is too large. One solution would to have the ability to use both px and rem sizes inside of `font()`

**Comment by chadoh** [comment]
@gh1dra 

> Why would we organize our styles around the `Text` component as it is already pretty generic? Maybe instead inside `theme` we have some predefined styles based off of the design system?

I want a single source of truth for typographic & spacing styles. As the design system changes, I'm hoping the aragonUI implementation only needs to update in one place, and both the `Text` and `Markdown` components will both receive the update. My understanding is that information about `Text` component styling currently lives within that component, so I was thinking of ways to make it shareable, so we can ensure `Markdown` styling stays in sync. Moving this information out of `Text` and into `theme` sounds good, too!

> Also the `rem` sizes don't really match 1-to-1 from your PR with the base `font-size: 15px`, let me know if the h1 being `great` is too large. One solution would to have the ability to use both px and rem sizes inside of `font()`

I wasn't expecting the aragonUI implementation to exactly match Autark's current implementation. For example, I used `em` and such when implementing Autark's version, but expect aragonUI's to use `px` everywhere. Once aragonUI has it built in, we will switch. 

I'm not totally sure what you mean by "have the ability to use both px and rem sizes inside of `font()`", but I doubt it's necessary.

Let me know if that makes sense, and if you have any other questions!

**Comment by sohkai** [comment]
Closed with https://github.com/aragon/aragon-ui/pull/395.
