### ISSUE TITLE
Missing components documentation

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#6]
- [ ] [AragonApp](https://github.com/aragon/aragon-ui/tree/master/src/components/AragonApp)
- [ ] Button modes (primary/secondary, compact, wide)
- [ ] [Card](https://github.com/aragon/aragon-ui/tree/master/src/components/Card)
- [ ] [AppBar](https://github.com/aragon/aragon-ui/pull/21)
- [ ] [EmptyStateCard](https://github.com/aragon/aragon-ui/pull/22)
- [ ] [Field](https://github.com/aragon/aragon-ui/pull/23)
- [ ] [SidePanel](https://github.com/aragon/aragon-ui/pull/24)
- [ ] [Tables](https://github.com/aragon/aragon-ui/pull/25)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x3ead1e4a7986df18dced802b5271b376f69e1d06c22efb8777da85614332d2c3](https://etherscan.io/tx/0x3ead1e4a7986df18dced802b5271b376f69e1d06c22efb8777da85614332d2c3)

**Comment by fiber-god** [comment]
Would these docs live on the main `README.md`, or in their own separate markdown files within a `docs/` folder of sorts (linked to by the main `README.md`)?

**Comment by sohkai** [comment]
We've currently set up per-component docs as .md files living beside the components (if it's the only component in the folder, then we usually use `README.md`; otherwise, `<ComponentName>.md`) and then add a gallery demo page as well in `gallery/src/pages/Page<ComponentName>.js`

How Button is documented is a good example:
- [src/components/Button/README.md](https://github.com/aragon/aragon-ui/blob/master/src/components/Button/README.md) contains most of the text
- [gallery/src/pages/PageButton.js](https://github.com/aragon/aragon-ui/blob/master/gallery/src/pages/PageButton.js) contains the demo of the component.

Ideally both the .md and demos should look like the already existing examples you'll find in the repo.

**Comment by fiber-god** [comment]
I'm gonna try my hand at resolving this issue!

**Comment by fiber-god** [comment]
@sohkai is there any movement in the bounty contract? For this and #35

**Comment by sohkai** [comment]
Hey @fiber-god, sorry about that! We will be approving them shortly (I believe #35 was sent to you?) :).
