### ISSUE TITLE
Add number formatting utilities

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#719]
From an offline discussion:

- `formatNumber()`: use `Intl.formatNumber()`
- `formatTokenAmount()`: build on top of `formatNumber()` and add some options to make it easier to format token amounts (e.g. see [this function](https://github.com/aragon/aragon-apps/blob/2ced965a1be54fb38809e332eba5b39322f5c32c/future-apps/payroll/app/src/utils/formatting.js#L12-L33))

**Comment by ECWireless** [comment]
Should the options be the exact same as the payroll formatting options (formatCurrency) you gave in the example, or are there specific options you have in mind for the UI formatTokenAmount util?

**Comment by bpierre** [comment]
@ECWireless I think we could adapt them to make it a bit simpler to use:

#### `pow`, `multiplier` and `decimals`
I think we could replace these three params by a single `decimals = 18`, since it is both defined by ERC-20 and widely used. Similarly to `amount`, this should be either a number, or any object with a `toNumber()` method (i.e. we should call `Number()` on it).

#### `amount`
This should be either a string, a `BigInt` instance, or any object with a .toString() method (i.e. we should call `String()` on it).

#### `rounding`
I think we could rename this to something like `displayDecimals`, `roundToDecimals`, `decimalPlaces`, or just `precision`?

#### `isIncoming`
I don’t think this is needed, we can use a sign on the BigInt + `displaySign` (or `signDisplay`) to determine that.

#### `displaySign`
We might want to name it `signDisplay` to align it with [the new `Intl.NumberFormat` API](https://github.com/tc39/proposal-unified-intl-numberformat#iii-sign-display).

<hr>

@sohkai @ECWireless  what would you guys think about naming the function `formatAmount()`? It might sound a bit generic, but I think there is enough context for authors to know what it is about. It would also make it clearer that we can use it to format currencies like USD as well.

**Comment by ECWireless** [comment]
Okay, most of that makes sense to me. The only thing I'm fuzzy on is: if `pow` and `multiplier` are being removed, couldn't decimals and rounding be combined into a simple `precision` option? (Since they essentially accomplish the same thing?)

**Comment by bpierre** [comment]
@ECWireless the two would be different. The idea would be to pass a token amount represented as an integer, requiring to indicate its number of decimals. Then, for display reasons, we want to round this number of decimals to a certain number.

Let’s take 3.43879238 ETH as an example: its value would be represented as `3438792380000000000n` (passed as `amount`), and the `decimals` param would let the function know where to put the decimal so we can get `3.43879238`. The `precision` param would tell the function that we only want to keep the last n digits in the decimals. For example with precision `2`, the displayed amount would be `3.44`.

**Comment by sohkai** [comment]
> what would you guys think about naming the function formatAmount()

I'm somewhat worried about `formatNumber()` and `formatAmount()` being mistaken, rather than the more verbose and obvious `formatTokenAmount()`.

On the point about formatting currencies, wouldn't you just use `formatNumber()` / `Intl.formatNumber()` to achieve that? Unless the currency has already been tokenized (e.g. USDC), I don't imagine people will be using arbitrary decimal points.

**Comment by bpierre** [comment]
Good points, let’s go for the more explicit `formatTokenAmount()` :+1:

**Comment by ECWireless** [comment]
It looks like `formatTokenAmount()` is a utility that's already used in Agent, Finance, and Payroll. Is it fine using the same name for this UI function? (I'm assuming this general UI function is meant to replace the specific `formatTokenAmount()` that already exist in Agent, Finance, and Payroll?)

**Comment by bpierre** [comment]
> I'm assuming this general UI function is meant to replace the specific `formatTokenAmount()` that already exist in Agent, Finance, and Payroll?

@ECWireless Yes, exactly! We can use the same name :+1:

**Comment by ECWireless** [comment]
Before I make any kind of pull request, I wanted to see if this is in the right direction (only slightly different from the functions in Payroll). Admittedly, I think I'm a little lost with how to use signDisplay if isIncoming is being removed.

`export function formatNumber(number) {
  return new Intl.NumberFormat('en-US', {minimumFractionDigits: 0,}).format(number)
}

export function formatTokenAmount(
  amount,
  symbol,
  decimals = 18,
  precision = 2,
  signDisplay = false
) {
  const number = round(
    (amount / Math.pow(10, decimals)),
    precision
  )
  const formattedNumber = formatNumber(number)
  const sign = signDisplay ? '+' : ''
  return `${sign}${formattedNumber} ${symbol}`
}`

**Comment by sohkai** [comment]
Closed with #728
